window.AIDAS_SUPABASE_CONFIG = {
  url: "https://tisenowyxvkirsxznmjr.supabase.co",
  anonKey: "sb_publishable_YFmH44cOriAjQM4RRWt-Gg_4NTtimQD",
  // Soft gate shared with lab members (visible in page JS — not real security).
  sharedPassword: "aidas12!@",

  // X (Twitter) "X Feed" tab. The daily job (scripts/ingest-xfeed.js) pulls recent posts
  // from these accounts via X's public syndication endpoint into papers/twitter-feed.json,
  // which the tab renders as native-style cards. Edit this list to change who appears.
  xAccounts: [
    // AI paper / news aggregators
    "_akhaliq",
    "arankomatsuzaki",
    "omarsar0",
    "TheTuringPost",
    // Frontier labs & orgs
    "OpenAI",
    "AnthropicAI",
    "GoogleDeepMind",
    "AIatMeta",
    "MistralAI",
    "huggingface",
    "deepseek_ai",
    "Alibaba_Qwen",
    "allen_ai",
    "NVIDIAAI",
    "lmarena_ai",
    // Researchers & well-known voices
    "karpathy",
    "ylecun",
    "drfeifei",
    "AndrewYNg",
    "sama",
    "JackClarkSF",
    "hardmaru",
    "giffmana",
    "rasbt",
    "srush_nlp",
    "_jasonwei",
    "percyliang",
    // Robotics
    "DrJimFan",
    "svlevine",
    "chelseabfinn",
    "pabbeel",
    "ericjang11",
    "RussTedrake",
    "xiao_ted",
    "physical_int",
    "RLWRLD_ai",
    "TheHumanoidHub",
    "robotsdigest",
    "robominyoung",
    "junfanzhu98",
    // More researchers, labs & venues
    "geoffreyhinton",
    "fchollet",
    "goodfellow_ian",
    "kchonyc",
    "ykilcher",
    "EMostaque",
    "gdb",
    "elonmusk",
    "bodonoghue85",
    "ssahoo_",
    "berkeley_ai",
    "JulianSaks",
    "eccvconf",
    "CVPR",
    // From the owner's feed
    "kevin_y_wu",
    "notmahi",
    "chris_j_paxton",
    "litian_liang",
    "gabriberton",
    "vai_viswanathan",
    "plastic_gear",
    "lukas_m_ziegler",
    "minchoi",
    "googlegemma",
    "tzedonn",
  ],
};
