window.AIDAS_SUPABASE_CONFIG = {
  url: "https://lcitqvajzdmewiwcmlek.supabase.co",
  anonKey: "sb_publishable_5F-zk-9tXGQDT9rL7D4rWQ_aZGS_6-G",
  sharedPassword: "aidas12!@",

  // X (Twitter) "X Feed" tab. The daily job (scripts/ingest-xfeed.js) pulls recent posts
  // from these accounts via X's public syndication endpoint into papers/twitter-feed.json,
  // which the tab renders as native-style cards. Edit this list to change who appears.
  xAccounts: [
    // AI paper / news aggregators
    "_akhaliq",
    "arankomatsuzaki",
    "omarsar0",
    "TheTuringPost",
    // Frontier labs & orgs
    "OpenAI",
    "AnthropicAI",
    "GoogleDeepMind",
    "AIatMeta",
    "MistralAI",
    "huggingface",
    "deepseek_ai",
    "Alibaba_Qwen",
    "allen_ai",
    "NVIDIAAI",
    "lmarena_ai",
    // Researchers & well-known voices
    "karpathy",
    "ylecun",
    "drfeifei",
    "AndrewYNg",
    "sama",
    "JackClarkSF",
    "hardmaru",
    "giffmana",
    "rasbt",
    "srush_nlp",
    "_jasonwei",
    "percyliang",
    // Robotics
    "DrJimFan",
    "svlevine",
    "chelseabfinn",
    "pabbeel",
    "ericjang11",
    "RussTedrake",
    "xiao_ted",
    // From the owner's feed
    "kevin_y_wu",
    "notmahi",
    "chris_j_paxton",
    "litian_liang",
    "gabriberton",
    "vai_viswanathan",
    "plastic_gear",
    "lukas_m_ziegler",
    "minchoi",
    "googlegemma",
    "tzedonn",
  ],
};
